### ISSUE TITLE
not working on IDEA.15...

### ISSUE THREAD

**Issue by pstephenwille** [johnlindquist/AceJump#53] opened 2015-11-19 19:57 UTC
looks like we need a bug fix again.

**Comment by Matsemann** [comment] 2015-12-03 14:38
Works fine here

**Comment by influenza** [comment] 2015-12-15 16:41
The plugin just creates a gray rectangle when activated. I'm also using the vim emulator.
![15dec2015-1141](https://cloud.githubusercontent.com/assets/770755/11816947/bc5116ae-a320-11e5-9f71-97185f6ecb36.png)

**Comment by pstephenwille** [comment] 2015-12-22 16:33
ugh...again!
idea-IU-143.1184.17

I put in a request to official integrate this plugin with IntelliJ.

**Comment by Forever-Young** [comment] 2016-01-15 12:02
Linux, PyCharm 5, creates rectangle but I must focus it with mouse first, otherwise key strokes go to the editor.

**Comment by dajnz** [comment] 2016-01-19 21:30
phpstorm 10.0.3 + vim plugin - the same issue. On hotkey only rectangles appears but nothing works

**Comment by pstephenwille** [comment] 2016-01-28 18:20
No fix yet?
John, are you alive?

**Comment by breandan** [comment] 2016-01-29 00:48
@pstephenwille, I'm running AceJump 2.0.5 on IU-143.1184.17 on Windows and can't reproduce this issue. Are you using Mac OS X? This might have something to do with the custom JDK introduced in 15 - need to investigate.

**Comment by pstephenwille** [comment] 2016-02-04 15:32
@breandan
I am on Ubunut latest with Java 1.8.0_72.  I just downloaded and tried the newest IDEA, with no change.  Sure would like to get this fixed as it's keeping my on IDEA-14

**Comment by marpe** [comment] 2016-02-05 14:42
I'm having this issue as well. Sama setup as @pstephenwille

**Comment by ebonet** [comment] 2016-02-10 12:32
Same issue on IntelliJ MacOs X build 143.1821. It shows a grey tooltip, and I need to type a letter for it to show the labels, that lead to the occurrences of that ketter.

**Comment by pstephenwille** [comment] 2016-02-13 00:51
Tested on win10/IDEA15, and it works fine.  Is this a Kotlin issue?

**Comment by shainegordon** [comment] 2016-02-26 10:24
same issue on windows 10/idea15

`ctrl+;` brings up a grey rectangle, and then I first need to push a button to make the jump overlays appear

**Comment by breandan** [comment] 2016-03-04 20:03
What should happen after pressing 'Ctrl+;'? Based on [this screencast](https://www.youtube.com/watch?v=yK8eM50DsAY), it looks like this behavior was as designed. User presses AceJump command, search box appears, user types character, jump labels appear, user types label, cursor jumps to position. Am I missing something? Tested AceJump 2.0.7 on IC-144.3600.7 on OS X El Capitan 10.11.3.

**Comment by Forever-Young** [comment] 2016-03-05 05:59
As I said before - I press Ctrl+;, box appears, I type character, it goes into editor, not into search box.
ArchLinux

**Comment by breandan** [comment] 2016-03-17 04:17
Try updating to [version 2.0.7](https://plugins.jetbrains.com/update/index?pr=&updateId=24725). This update contains PR #43, addressing a focus issue that was never released. Please report back if the issue persists, or introduces a regression (tested on Mac OS X and Windows). Thanks!

**Comment by breandan** [comment] 2016-03-17 04:23
Closing as duplicate of #44. Please feel free to continue the discussion there.

**Closed by breandan** 2016-03-17 04:23 UTC
