### ISSUE TITLE
Ubuntu Focus issue

### ISSUE THREAD

**Issue by markmandel** [johnlindquist/AceJump#39] opened 2014-02-13 23:54 UTC
Sorry to give you yet another focus issue on Ubuntu.

Video here:
https://dl.dropboxusercontent.com/u/16200445/acejump-focus.ogv

You can see that the focus immediately got back to thee editor as soon as the input box shows up.

Env:
Ubuntu 13.10, 64Bit
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
IntelliJ 13.1 EAP (idea-IU-134.1007)

Let me know if I can provide any more information 

Just noted - AceJump seems to be fine in 13.0, it just doesn't want to work in 13.1. Quick Jump has exactly the same issue FYI.

**Comment by karanr** [comment] 2015-05-31 02:33
This issue still persists. The focus immediately goes back to the editor making the plugin pointless. Ubuntu 14.10, RM 7.1.2.

**Comment by Centaur** [comment] 2015-06-02 02:23
I have followed the author's suggestion and been using `emacsIDEA` plugin instead.

**Comment by breandan** [comment] 2016-03-17 04:32
Closing as duplicate of #44. Please see the [most recent update](https://github.com/johnlindquist/AceJump/issues/53#issuecomment-197686309), which contains @Centaur's fix #43. Thanks!

**Closed by breandan** 2016-03-17 04:32 UTC
