### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by arg20** [johnlindquist/AceJump#44] opened 2014-04-24 15:11 UTC
I can't figure out what is causing this but when I press ctrl + ; the square box appears, but as I type any letter so that the options are displayed, it will continue to type in the javascript file instead of displaying any options. I cannot find out what is causing this problem. If I type "a" so I can jump to any location that begins with an "a", instead I get the "a" underneath the small black box that appears  when the plugin is triggered. Is anyone else experiencing this? I'm using Webstorm 8.0.1.

**Comment by EoinGriffin-AI** [comment] 2015-04-01 22:57
+1 for this issue. Using Ubuntu 14.10 and IntelliJ IDEA 14.1

I was fairly sure this worked a few days ago, so it might have been broken when I upgraded from IntelliJ 14.0 to 14.1

**Comment by vysinsky** [comment] 2015-04-02 07:10
Yeah, the problem is back in PhpStorm EAP 9 - the "input" does not get focus and you write into the code.

**Comment by maklemenz** [comment] 2015-04-02 14:52
Same issue using the just released Webstorm 10 and Ubuntu 14.10. Same goes with quickjump.

**Comment by johnlindquist** [comment] 2015-04-02 16:32
Can you guys try the AceJump features from the emacsIDEAr plugin? 
https://plugins.jetbrains.com/plugin/7163?pr=idea

I actually use that now (and contribute to it) because it's better written and more fully featured than mine/this.

**Comment by vysinsky** [comment] 2015-04-03 07:35
Centaur's fork works. But I don't know how up-to-date it is.

**Comment by EoinGriffin-AI** [comment] 2015-04-06 19:01
the emacsIDEA plugin does work... so does this mean this AceJump plugin is now dead? Or will it be fixed for this issue?

**Comment by metyl** [comment] 2015-09-03 12:40
The emacsIDEAs seems to work, latest 15 EAP at OSX

**Comment by levilindsey** [comment] 2015-11-08 20:52
@johnlindquist Since this plugin doesn't work with the current IDE versions and you recommend the emacsIDEAs plugin instead, could you update the documentation for your plugin to mention this? It's harder to find the solution through your repo's issues list.

**Comment by andresdominguez** [comment] 2015-11-08 22:09
@levilindsey use this one  https://github.com/Centaur/AceJump I have been using it for several months.

I spoke with @johnlindquist a couple of weeks ago and I asked about this bug. Maybe we will get some love?

**Comment by breandan** [comment] 2016-03-17 04:29
[Version 2.0.7](https://plugins.jetbrains.com/update/index?pr=&updateId=24725) contains @Centaur's PR #43, which addresses the lost focus issue. Please report any issues you encounter.

**Comment by breandan** [comment] 2016-07-17 04:11
As there have been no further reports of lost focus, I am closing. Please open another ticket for reporting related issues.

**Closed by breandan** 2016-07-17 04:11 UTC
