### ISSUE TITLE
Performance regression since 3.3.2

### ISSUE THREAD

**Issue by helmus** [johnlindquist/AceJump#191] opened 2017-09-16 23:08 UTC
First of all, thank your for continuously maintaining this plugin, I really love it !

However, ever since 3.3.2 ace jumps searches the entire page. I believe this is the reason there is now a 100 - 200ms delay on the search ( depends on the document I suppose ). This is really annoying, the purpose of acejump is to be faster !

I actually believe that searching the entire document defeats the purpose of ace jump. When I use ace jump I use it to jump to a visible location in my current editor. If if where jumping to a location not visible on the screen  I would use search, search makes more sense here because it's unlikely that a single letter search trough ace jump will land me on my target in the whole document.

**Comment by breandan** [comment] 2017-09-16 23:32
Thanks @helmus, I appreciate your feedback. This is an issue we are acutely aware of. Working on a few solutions here. First is to implement a toggle switch for full-page search. And second is to speed up full-page search, as the current implementation is blocking. I am a full-time student, so I can't promise any time frame for deploying these features, but if you install the old version manually (via the plugin repository](https://plugins.jetbrains.com/plugin/7086-acejump)) the tagger should be much more responsive. Closing as a duplicate of #161.

**Closed by breandan** 2017-09-16 23:32 UTC
