### ISSUE TITLE
AceJump will crash when i type 'control+;' 

### ISSUE THREAD

**Issue by NathanXuns** [johnlindquist/AceJump#199] opened 2017-10-18 02:42 UTC
When i type 'control + ;' in my android studio (Version 2.3.3) , android studio will threw an Plugin Error : 'AceJump threw an uncaught , NoSuchMethodError. Disable Plugin'.My AceJump Version is V3.4.2 . And I have tried uninstall Acejump Plugin then reinstalled , but not works.So,how can i fix this , my email is 'nathanxuns@gmail.com'

![2017-10-18_10-23-53](https://user-images.githubusercontent.com/10072368/31699085-8f62e94c-b386-11e7-889b-23d80b669b9c.png)

**Comment by breandan** [comment] 2018-03-06 02:50
This is probably a duplicate of #200. Please reopen if you encounter a different stack trace. Thanks!

**Closed by breandan** 2018-03-06 02:50 UTC
