### ISSUE TITLE
acejump not working On IDEA 13 or 14 version

### ISSUE THREAD

**Issue by lidaling** [johnlindquist/AceJump#51] opened 2015-05-26 10:30 UTC
I have install the acejump plugin and ideavim plugin On IDEA 14 .I can see the box when I type the shortcut key call acejump,but when I type one character ,no tips show,either I disable the ideavim plugin or install a IDEA 13 version.
I am using Debian 8 .
Anyone can help me ,please.
: )

**Comment by samidarko** [comment] 2015-06-29 10:38
Almost same with WebStorm 10.0.4 + jdk 1.8.0_45 on Gentoo. I can see the box with "Ctrl+;" but no characters appears when I'm keying. Thanks for your help :)

**Comment by deathmaz** [comment] 2015-07-18 17:07
Same here on Phptorm 9 with ideavim plugin and Arch linux.
Acejump works if I click my mouse right to the box, that appears after "Ctrl+;".

**Comment by cold147** [comment] 2015-08-17 10:46
Same here with phpstorm 9 without ideavim

**Comment by magicyuuu** [comment] 2015-09-01 01:48
Same on Clion 1.1 with ideavim...

**Comment by pyeye** [comment] 2015-09-18 14:17
Same here on pycharm 4.5 without ideavim

**Comment by Charminbear** [comment] 2015-10-17 14:14
Same here on IntelliJ 14.1.5 on Linux Mint Mate 17.2

**Comment by nelsou** [comment] 2015-12-14 14:20
The problem still exist ... 14.1.5 Ultimate - JRE 1.8.0

**Comment by breandan** [comment] 2016-03-17 04:19
Closing as duplicate of #53. Please see the [most recent update](https://github.com/johnlindquist/AceJump/issues/53#issuecomment-197686309).

**Closed by breandan** 2016-03-17 04:19 UTC
