### ISSUE TITLE
No focus in small window =(

### ISSUE THREAD

**Issue by mrArtCore** [johnlindquist/AceJump#56] opened 2016-02-26 12:29 UTC
Hi there ! 
I regret to say that small window not active when pressed "ctrll + ;" I have to use mouse for activate it =( 
All like in this issue -> https://github.com/johnlindquist/AceJump/issues/41
Android Studio 1.5.1, Ubuntu 14.04

**Comment by iamfreee** [comment] 2016-03-12 18:11
Arch linux, Phpstorm 10. 

Same problem.

**Comment by breandan** [comment] 2016-03-17 04:20
Closing as duplicate of #53. Please see the [most recent update](https://github.com/johnlindquist/AceJump/issues/53#issuecomment-197686309).

**Closed by breandan** 2016-03-17 04:20 UTC
