### ISSUE TITLE
Jump to position labels are misaligned in WebStorm 2017.2

### ISSUE THREAD

**Issue by darryldaniel** [johnlindquist/AceJump#176] opened 2017-07-25 07:41 UTC
After installing the new WebStorm, I noticed that whenever I tried to use AceJump I cannot see the labels of the position that I want to navigate to clearly. They seem to be misaligned (see image below). I have updated to the latest AceJump (version 3.4.0)

![image](https://user-images.githubusercontent.com/11090424/28561007-f67bbe6c-711c-11e7-94db-d632f75e6a0c.png)

**Comment by mikeerickson** [comment] 2017-07-26 04:15
@darryldaniel  I am seeing the same thing here, can't figure out how to "fix" the issue?

@johnlindquist Do you have any insight as to the cause (and possible fix)

**Comment by johnlindquist** [comment] 2017-07-26 04:21
Nope, I handed this over to @breandan a looooooong time ago. He's the reason it's alive and kickin'.

**Comment by mikeerickson** [comment] 2017-07-26 05:21
@johnlindquist well then, sorry to bother you :)

@breandan any idea what can be done to fix this issue?

**Comment by breandan** [comment] 2017-07-26 14:57
@mikeerickson I'll see what I can do. Thanks for reporting!

**Comment by breandan** [comment] 2017-07-26 17:19
Unable to reproduce. Can you submit any further details? Do you have other plugins installed that might paint to the editor? 

<img width="817" alt="screen shot 2017-07-26 at 1 17 50 pm" src="https://user-images.githubusercontent.com/175716/28634329-e40ccf94-7204-11e7-8fd8-bcb32dcca1fa.png">

**Comment by mikeerickson** [comment] 2017-07-26 17:28
@breandan I guess the only thing I have would be the Material Theme but it has always worked in the past.  I (unlike original submitter) am using PHPStorm EAP 2017.2.1 (just installed the new EAP this morning).

**Comment by mikeerickson** [comment] 2017-07-26 17:28
@breandan I would be most willing to help debug this, but not sure where to start.

**Comment by breandan** [comment] 2017-07-26 17:44
Okay, now I know what's happening: #98 strikes again. We should have a fix up soon. Thanks!

**Comment by mikeerickson** [comment] 2017-07-26 18:30
Awesome, thanks!

**Comment by mikeerickson** [comment] 2017-07-26 18:31
@breandan  Never know how much you use something until it is gone :-)

**Comment by darryldaniel** [comment] 2017-07-27 05:33
Thanks so much @breandan!

**Comment by mikeerickson** [comment] 2017-08-01 18:40
@breandan The latest available version for download is 3.4.0?   How long does it take to propagate so it can be installed? I am assuming it is cured in 3.4.1, but unable to see (install) that version

![image](https://user-images.githubusercontent.com/183153/28841158-23039efa-76ae-11e7-8344-e347e478310a.png)

**Comment by breandan** [comment] 2017-08-02 00:20
@mikeerickson Haven't shipped the fix just yet, but it will be in the next version which will be later this week. If you're in a pinch, you can always change your line spacing to 1.0 or roll back to a previous version on the plugin repository: 

<img width="809" alt="screen shot 2017-08-01 at 8 18 31 pm" src="https://user-images.githubusercontent.com/175716/28852375-a0f354a2-76f6-11e7-96e3-1ca6c5694077.png">

**Comment by mikeerickson** [comment] 2017-08-02 03:39
@breandan I managed to find 3.3.2 and am now using that version so all is good for now.

**Comment by mikeerickson** [comment] 2017-08-02 03:44
@breandan how do I get to the location you supplied in screenshot

**Comment by chen4342024** [comment] 2017-08-12 04:18
![image](https://user-images.githubusercontent.com/3050009/29237777-076d8ac2-7f58-11e7-9a4c-959fc199dcfa.png)

I have the same problem , and i change Line spacing to 1.0 . it still has radius

**Comment by psumstr** [comment] 2017-08-17 21:49
Same problem here. Line Spacing set to 1.0, Material Theme, Webstorm 2017.2.2

**Comment by mikeerickson** [comment] 2017-08-18 01:46
@psumstr you can downgrade to a previous version (I downgraded to 3.3.2) to get it working again. Version 3.4.1 has fixed this as well, but it has yet to be released.  So, the only working solution is to downgrade from 3.4.0

**Comment by mikeerickson** [comment] 2017-08-23 21:12
@breandan any update on this... I am reminded to update every time I check updates :)

**Comment by viktorivanov** [comment] 2017-08-31 12:48
I am having the same issue.
_Using PhpStorm 2017.2.1 with Material Theme_

**Comment by mikeerickson** [comment] 2017-08-31 15:03
@viktorivanov While this has been fixed in 3.4.1 (which has yet to be released) I have reverted to v3.3.2 where all works fine.  This problem was a regression part of 3.4.0 release

So, downgrade 3.3.2 and all will be fine.

**Comment by viktorivanov** [comment] 2017-09-01 06:56
Ah, nice! Thank you @mikeerickson 👍

**Comment by altryne** [comment] 2017-10-14 03:32
Hey guys, any updates on this? I'm really having troubles using this plugin with the offset with the material theme

**Comment by mikeerickson** [comment] 2017-10-14 17:05
@altryne  while this has yet to be released, I have reverted to v3.3.2 where all works fine. This problem was a regression part of 3.4.0 release

So, downgrade 3.3.2 and all will be fine.

**Closed** 2017-10-15 00:22 UTC
Labels: bug

**Comment by breandan** [comment] 2017-10-15 00:32
Tag alignment should be fixed in the latest build. Please feel free to reopen if this reappears. Thanks.

**Comment by darryldaniel** [comment] 2017-10-16 05:36
Thanks @breandan, great work on this, I really enjoy AceJump!
