### ISSUE TITLE
Problems with Intellij 14

### ISSUE THREAD

**Issue by curdinB** [johnlindquist/AceJump#47] opened 2014-12-11 08:06 UTC
Hi

There seams to be an issue with the new Intellij 14 release. When pressing ctrl+; , the input field is shown but without a cursor (not even when i click into the input field) and the typed character is also not shown. Nevertheless it works except of multi character input, which may be broken or i just cant figure out how to use it (cant find any shortcut so im guessing its possible per default)

Greetings and thanks for the great plugin

**Comment by cezary-draus** [comment] 2015-03-26 11:12
Same problem with 14.1 in 14.0 it works on my env.

**Comment by rocketraman** [comment] 2015-03-29 19:42
Are you using [AceJump.zip](https://github.com/johnlindquist/AceJump/blob/master/AceJump.zip) in the repository or the one downloaded from plugin manager? The plugin manager appears to have an out of date version. The one from the repo works for me on Linux with 14.1.

**Comment by cezary-draus** [comment] 2015-03-30 07:53
It works! Thanks.

2015-03-29 21:42 GMT+02:00 Raman Gupta <notifications@github.com>:

> Are you using AceJump.zip
> <https://github.com/johnlindquist/AceJump/blob/master/AceJump.zip> in the
> repository or the one downloaded from plugin manager? The plugin manager
> appears to have an out of date version. The one from the repo works for me
> on Linux with 14.1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/johnlindquist/AceJump/issues/47#issuecomment-87461918>
> .
>



-- 
Pozdrawiam,
Cezary Draus

**Comment by pstephenwille** [comment] 2015-04-03 20:24
Thank you @rocketraman 
Works on ubu14.10

I did have to drill into AceJump-master to unzip AceJump, which contained the two .jars, to swap out with the ones in Plugin/AceJump.

~~~
AceJump.jar
kotlin-runtime.jar
~~~

**Comment by rocketraman** [comment] 2015-10-31 06:05
Note: AceJump.zip in the repository mentioned above seems to work on IntelliJ 15 as well.

**Comment by breandan** [comment] 2016-03-17 04:19
Closing as duplicate of #53. Please see the [most recent update](https://github.com/johnlindquist/AceJump/issues/53#issuecomment-197686309).

**Closed by breandan** 2016-03-17 04:19 UTC
