### ISSUE TITLE
AceJump  dosen't work in ideavim sometimes

### ISSUE THREAD

**Issue by hujianxin** [johnlindquist/AceJump#107] opened 2016-11-21 05:19 UTC
I binded AceJumpAction to `<Space>jj` and AceJumpLineAction to `<Space>jl`. When I hit `<Space>jj` too quickly, AceJumpAction will not work, however AceJumpLineAction always works well.

IntelliJ IDEA version is 2016.2.6.

**Comment by hujianxin** [comment] 2016-11-21 05:23
If I change AceJumpAction from `<Space>jj` to `f` , this problem will disappear. But I really like `<Space>jj`

**Comment by hujianxin** [comment] 2016-11-21 05:32
My fault, binding it to `f` also causes this problem.

**Comment by thirtythreeforty** [comment] 2016-11-22 22:52
Yep, I'm seeing this too with it bound to `s`.  It should be noted that `Ctrl-;` still works fine, though.

**Comment by thirtythreeforty** [comment] 2016-11-22 22:59
This might actually be a duplicate of #77.

**Comment by breandan** [comment] 2016-11-23 18:09
There appears to be a considerable delay when remapping IdeaVim keys to AceJump. This may be due to the [TypedActionHandler](https://github.com/JetBrains/ideavim/blob/master/src/com/maddyhome/idea/vim/VimTypedActionHandler.java) delegation as Andrey [mentions](https://github.com/johnlindquist/AceJump/issues/77#issuecomment-256316791), but will need further investigation before we can issue a fix. Seems like @hughnguy reported the issue first, but let's leave both tickets open in case they are unrelated. Thanks @hujianxin and @thirtythreeforty for corroborating.

**Comment by hujianxin** [comment] 2016-11-24 12:36
@breandan Thanks for your reply, there is something wrong in my description. `<Space>jl` for `AceJumpLineAction` is alse not working.

**Comment by hujianxin** [comment] 2016-11-24 12:40
I have used `emacsIDEA` plugin. This plugin also has a function like `AceJumpAction`. But the problem described above does not appear when using it.

**Comment by breandan** [comment] 2017-01-04 01:04
As mentioned [here](https://github.com/johnlindquist/AceJump/issues/77#issuecomment-270268856) I recently made a bunch of changes to support IdeaVim compatibility, and I have not witnessed this issue since. 

@hujianxin @thirtythreeforty Can you reproduce this behavior on the latest version of AceJump? Thanks.

**Comment by hujianxin** [comment] 2017-01-04 01:25
@breandan I just tested this on Intellij 2016.3.2 and latest ideavim, and I couldn't reproduce it anymore, This bug maybe disappear. Thanks for your great work!

In fact, I have not used ideavim for long time.

**Comment by breandan** [comment] 2017-01-04 03:29
Glad to hear, thanks for your feedback. Feel free to reopen if issue persists.

**Closed by breandan** 2017-01-04 03:29 UTC

**Comment by thirtythreeforty** [comment] 2017-01-04 07:34
Just wanted to chime in and confirm that the issue seems to be fixed for me as well (I use IdeaVim daily).  Thanks!
