### ISSUE TITLE
Jump locations not aligned in Dracula theme

### ISSUE THREAD

**Issue by kamranahmedse** [johnlindquist/AceJump#189] opened 2017-09-14 16:13 UTC
Jump locations are not visible in Dracula theme

![image](https://user-images.githubusercontent.com/4921183/30441030-44b14ab8-9989-11e7-8be3-5c6b528a5368.png)

**Comment by breandan** [comment] 2017-09-17 02:14
This is a duplicate of #176, and is caused by your line spacing. Thanks for reporting.

**Closed by breandan** 2017-09-17 02:14 UTC
