### ISSUE TITLE
Editor is already disposed crash

### ISSUE THREAD

**Issue by igorwojda** [johnlindquist/AceJump#183] opened 2017-08-16 14:12 UTC
Android Studio 2.3.3.
100% repetable, sometimes I able to use this plugin once. Aftre switching to other file thsi happens:

```Editor is already disposed
com.intellij.openapi.util.TraceableDisposable$DisposalException: Editor is already disposed
	at com.intellij.openapi.util.TraceableDisposable.throwDisposalError(TraceableDisposable.java:94)
	at com.intellij.openapi.editor.impl.EditorImpl.throwDisposalError(EditorImpl.java:871)
	at com.intellij.openapi.editor.impl.view.TextLayoutCache.checkDisposed(TextLayoutCache.java:181)
	at com.intellij.openapi.editor.impl.view.TextLayoutCache.getLineLayout(TextLayoutCache.java:140)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.setFragmentIterator(VisualLineFragmentsIterator.java:159)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.init(VisualLineFragmentsIterator.java:150)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.<init>(VisualLineFragmentsIterator.java:102)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.<init>(VisualLineFragmentsIterator.java:37)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator$1.iterator(VisualLineFragmentsIterator.java:43)
	at com.intellij.openapi.editor.impl.view.EditorCoordinateMapper.visualToLogicalPosition(EditorCoordinateMapper.java:141)
	at com.intellij.openapi.editor.impl.view.EditorView.visualToLogicalPosition(EditorView.java:152)
	at com.intellij.openapi.editor.impl.EditorImpl.visualToLogicalPosition(EditorImpl.java:4100)
	at com.intellij.openapi.editor.impl.EditorImpl.visualToLogicalPosition(EditorImpl.java:4095)
	at com.johnlindquist.acejump.search.AceUtilKt.visualLineToLogicalLine(AceUtil.kt:161)
	at com.johnlindquist.acejump.search.AceUtilKt.getView(AceUtil.kt:70)
	at com.johnlindquist.acejump.control.Handler.restoreScroll(Handler.kt:233)
	at com.johnlindquist.acejump.control.Handler.restoreSettings(Handler.kt:227)
	at com.johnlindquist.acejump.control.Handler.reset(Handler.kt:196)
	at com.johnlindquist.acejump.view.Model.setEditor(Model.kt:31)
	at com.johnlindquist.acejump.control.AceAction.actionPerformed(AceAction.kt:16)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:609)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)```


Mabye related to
https://github.com/johnlindquist/AceJump/issues/178

**Comment by breandan** [comment] 2017-08-30 19:14
Closing as a duplicate of #175, thanks for reporting.

**Closed by breandan** 2017-08-30 19:14 UTC
