### ISSUE TITLE
What makes AceJump awsome in Emacs

### ISSUE THREAD

**Issue by favetelinguis** [johnlindquist/AceJump#95] opened 2016-11-02 10:23 UTC
I have used acejump in Emacs and the three features that makes it a killer plugin there are as follows.

1. Works over multiple windows
2. Only searches first letter in word to make is (much) easier to navigate
3. Matches closest are reaced using homerow keys assuming QWERTY keyboard

Are there any plans on extending Intellij version to do something like this also or are we happy with things as there are?

**Comment by breandan** [comment] 2016-11-02 12:10
Thanks for the feedback. In theory, all three features should be possible in a future release.

1. On the roadmap, possibly a duplicate of #71. PRs are highly welcome!
2. We could flip a switch to make this available, but it would need further testing to work in all cases. The current mechanism matches one letter inside a word, but it is not guaranteed to match the first. cf. https://github.com/johnlindquist/AceJump/issues/79#issuecomment-255611633 for clarification. This would make more sense, if possible. The only downside is that fewer tags are available to use, the earlier tags are assigned. A workaround is to type the next letter in the word, ie. "wo" rather than just "w". In either case, total keystrokes should remain unchanged on average.
3. It may be possible to use homerow keys for nearby matches. How do you define "matches closest"? By similarity to current word, by cursor distance? Is there any way we can be sure that nearby jumps are most frequent? Or is there another metric to estimate the most common jump locations based on the current cursor position? Our goal is to minimize the average time required for a jump, on average.

Thanks for using AceJump, further suggestions are highly appreciated!

**Comment by favetelinguis** [comment] 2016-11-03 07:21
Thank for the work on this plugin!

1. Fantastic!
2. Sounds like a config setting would be nice, maybe one could set a custrom regexp in config for what to match on?
3. Intersting question, witout user data it is hard to say. My guess is that closeness to cursor is the most important since the eyes would scan this area more frequently? But if we only would jump to first letter in word having 10keys on homerow would take us a long way and most often we will not get more then ~16matches wich i would say is the limit for the easiest to reach keys (homerow + e r i o w u)?

**Comment by breandan** [comment] 2017-07-04 15:25
Breaking this up into separate tickets.

1. Created another ticket #144.
2. Partially implemented, see also #28. 
3. Duplicates #28.

**Closed by breandan** 2017-07-04 15:25 UTC
Labels: enhancement, feature
