### ISSUE TITLE
Webstorm 2017.3.2 plugin crash

### ISSUE THREAD

**Issue by ioanlucut** [johnlindquist/AceJump#208] opened 2017-12-28 15:10 UTC
Since the last update of the Webstorm, the AceJump plugin crashes.
```
Could not initialize class com.johnlindquist.acejump.view.Model
java.lang.NoClassDefFoundError: Could not initialize class com.johnlindquist.acejump.view.Model
	at com.johnlindquist.acejump.control.AceAction.actionPerformed(AceAction.kt:24)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.g(IdeKeyEventDispatcher.java:479)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Webstorm 2017.3.2
Build WS 173.4127.31

**Comment by pejaham** [comment] 2018-01-31 10:59
I get the exact same error in IntelliJ build 2017.3.4 (build 173.4548.28), Linux 16.04.

**Comment by breandan** [comment] 2018-03-06 03:06
This issue is a duplicate of #130. Thanks for reporting!

**Closed by breandan** 2018-03-06 03:06 UTC
Labels: bug
